In [1]:
import pandas as pd

In [40]:
#Reading the data and outputing the first 5 rows
# The dataset has 10841 records and 13 rows
raw = pd.read_csv("googleplaystore.csv")
raw.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [41]:
# Checking the tail as well
raw.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

#### T1: Checking structure

In [ ]:
# raw now is our dataframe
# So from that we check it's Structure
print("Index: ", raw.index)
print("Columns: ", raw.columns)         # Labels and Order

Index:  RangeIndex(start=0, stop=10841, step=1)
Columns:  Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [63]:
# Testing how to access columns and rows
# Reminder, when you use dot notation, you put a dot - this produces a series object
# When you use brackets, either double or single then you don't need the dot - double columns = Dataframe
display(raw[["App", "Current Ver"]])

# Tesing for rows now and only deciding to show the Rating column
display(raw.query("Rating == None")[["Rating", "Android Ver"]])

                                                     App         Current Ver
0         Photo Editor & Candy Camera & Grid & ScrapBook               1.0.0
1                                    Coloring book moana               2.0.0
2      U Launcher Lite – FREE Live Cool Themes, Hide ...               1.2.4
3                                  Sketch - Draw & Paint  Varies with device
4                  Pixel Draw - Number Art Coloring Book                 1.1
...                                                  ...                 ...
10836                                   Sya9a Maroc - FR                1.48
10837                   Fr. Mike Schmitz Audio Teachings                 1.0
10838                             Parkinson Exercices FR                 1.0
10839                      The SCP Foundation DB fr nn5n  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology  Varies with device

[10841 rows x 2 columns]

Empty DataFrame
Columns: [Rating, Android Ver]
Index: []

In [15]:
raw

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [ ]:
# So we are checking the dataframe's information so see where the missing values are
raw.info()

# We see that Rating is missing a lot of values 9367 out of 10841
# Type is 10840 out of 10841
# Content Rating is also 10840 out of 10841
# Current Ver is 10833 out of 10841
# and Lastly Androud Ver is 10838 out of 10841

# From more examination I see that Reviews is a str (I don't think it should be)
# Size should also not be a string
# Installs as well
# PRICE SHOULD DEFINITELY NOT BE A STRING
# Last Updated should be a date

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [ ]:
# What is the dataframe's shape and size?
raw.size        # (total number of elements)
raw.shape       # (rows and columns)

(10841, 13)

In [ ]:
# nunique returns the number if unique data items in each column
# Maybe this one isn't the most useful but it can help in some way
raw.nunique()

App               9660
Category            34
Rating              40
Reviews           6002
Size               462
Installs            22
Type                 3
Price               93
Content Rating       6
Genres             120
Last Updated      1378
Current Ver       2832
Android Ver         33
dtype: int64

In [ ]:
# describe() returns statistical information for each numeric column
# this will only work with Rating since rating is the only numeric column (float64)
raw.describe()

# hint - describe() will display in rows but describe().T will describe in columns

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [39]:
# Accessing Columns and rows

msising_ratings_count = raw.query("Rating == None").isna()
print(msising_ratings_count)

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

## Checking if first 3 columns are present

In [78]:
# We are creating a new DataFrame called checking errors to work with finding errors
checking_errors = pd.DataFrame(raw)

first_3_column = checking_errors[["App", "Category", "Rating"]]
category_column = checking_errors["Category"]
rating_column = checking_errors["Rating"]

missing_names = first_3_column["App"].isna()
missing_category = first_3_column["Category"].isna()
missing_rating = first_3_column["Rating"].isna()
# isna() detects missing values - True mean values are absent

# True adds 1 to the sum and False adds 0
missing_names_count = missing_names.sum()
missing_category_count = missing_category.sum()
missing_rating_count = missing_rating.sum()

# Outputing all our results
display(first_3_column)                # We see that all records are false so there are no missing values
print("Missing names: ", missing_names_count)                           # sums up to 0 because there is no missing values
print("Missing categories: ", missing_category_count)
print("Missing ratings: ", missing_rating_count)

# ---------------------- Results -----------------------
# So after inspecting the names of the App columns. I have found that there are no missing values
# All are present, so we recognise that all object are there

,App,Category,Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1
1,Coloring book moana,ART_AND_DESIGN,3.9
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3
...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0
10838,Parkinson Exercices FR,MEDICAL,NaN
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5

Missing names:  0
Missing categories:  0
Missing ratings:  1474